sb-ai-lab/HypEx

- hypex/dataset/backends/pandas_backend.py
- hypex/dataset/base.py
- hypex/dataset/dataset.py
- hypex/dataset/tutorial_dataset.ipynb
* index - ds.index 
* unique() - ds[column].unique() 
* get_columns_by_roles - ds.get_columns_by_roles(Role) or ds.get_columns_by_roles([Role, Role])
> added index, unique, get_columns_by_roles,

- hypex/dataset/backends/pandas_backend.py
- hypex/dataset/base.py
- hypex/dataset/dataset.py
- tutorial_dataset.ipynb
Bug: 
* Fixed `apply` and `map` work 
Feature: 
* added `create_empty()` to dataset 
Usage: ds = Dataset('pandas').create_empty(indexes, columns)
> New features 

- hypex/dataset/backends/pandas_backend.py
- hypex/dataset/base.py
- hypex/dataset/dataset.py
- tutorial_dataset.ipynb
**Feature Description**
Locker and ILocker: Added class Locker and ILocker to Dataset to perform usage of loc and iloc like in pandas DataFrames.
loc and iloc: Added functions loc and iloc to PandasBackend to perform loc and iloc in pandas.
add_column: Added function add_column for addind column to data with role. 
**Usage:** 
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
ds = Dataset(df, roles={TargetRole: 'a', PreTargetRole: 'b'}) 
ds.loc[:, 'a'] 
ds.add_column([7, 8, 9], {'c': TargetRole})
> FEATURES loc, iloc, add_column 

- hypex/dataset/backends/pandas_backend.py
- hypex/dataset/base.py
- hypex/dataset/dataset.py
- hypex/dataset/roles.py
- tutorial_dataset.ipynb
* Removed `add_to_stats_fields` and  `add_to_additional_fields`
* Changed abstract metod `add_column` in `DatasetBase` 
* Override add_column in Dataset `add_column(self, data, name: Union[str, int, List], role: ABCRole)` 
* In `set _value` in case `analysis_tables` added function `add_to_analysis_tables`
> [FEATURE] add_column, set_value

- hypex/algorithms/faiss_matcher.py
- hypex/matcher.py
- hypex/utils/validators.py
Resolves #34 
This pull request introduces a new feature for handling emissions in data analysis within the HypEx framework. The feature aims to automate the identification and management of extreme outliers (emissions) that can significantly affect the reliability of analysis results.
- Added a new function `emissions` to automatically detect and handle emissions based on the 1st and 99th percentiles.
- Integrated the emissions handling feature into the existing data preprocessing pipeline, ensuring seamless operation with current functionalities.
- Included options for users to customize the handling method, including removing emissions or adjusting them according to predefined rules.
```python
def emissions(df, treatment, is_treated, outcome, low, high):
```
- Addresses user feedback …
> [FEATURE] Implement Emissions Handling in HypEx

- hypex/algorithms/faiss_matcher.py
Close #36 
This PR addresses an issue where Cholesky decomposition fails due to the matrix not being positive definite in certain groupings of the data. The fix involves adjusting the dataframe by removing categories that prevent successful decomposition.
- Implemented a preprocessing step to check for and exclude groupings that lead to non-positive definite matrices.
- Added logs to inform the user about excluded groupings and potentially duplicated columns in the test and control groups.
- Enhanced stability and reliability of the matching process by ensuring Cholesky decomposition can always be performed.
- Extensive testing was conducted with datasets known to cause the original issue, confirming that the fix prevents the `LinalgError` and allows successful execution.
- Validation …
> [FIX] Cholesky Decomposition Adjustment

- hypex/ab_test/aa_tester.py
- New function `calc_imbalanced_sample_size` in `AATest` class to calculate necessary sample sizes for control and test groups in studies with imbalanced group sizes.
This PR introduces the `calc_imbalanced_sample_size` function, which calculates the required sample sizes for control and test groups to achieve a specified power level. This function is particularly useful for experimental designs where the control and test groups are expected to be of different sizes. It supports both binary and continuous outcome data, calculating the necessary sample size based on the expected mean outcome in the test group, the proportion of the control group, and the desired power of the test.
In many fields, including marketing and clinical trials, experiments often involve groups of different sizes. …
> [FEATURE] Implement Imbalanced Sample Size Calculation

- pyproject.toml
More here #46 
We are excited to announce that this pull request brings official support for Python 3.11 and 3.12 to HypEx. In our continuous effort to stay up-to-date with the latest Python releases, we have made necessary updates and improvements to ensure compatibility with these newer versions. This change aims to empower our users to leverage the latest features and performance improvements offered by Python 3.11 and 3.12 while using HypEx for their data science projects.
- Conducted thorough testing of HypEx on Python 3.11 and 3.12 environments to identify and address any compatibility issues.
- Updated the project's dependency specifications to include support for Python 3.11 and 3.12, ensuring that all dependencies are compatible with these versions.
- Made code adjustments where …
> Added support 3.11 and 3.12. Moved from alpha to beta. Updated versions

- hypex/ab_test/limit_distribution.py
More here #51 
This pull request addresses a critical performance optimization and a bug fix in the `limit_distribution_function` of the HypEx library. Previously, users experienced longer than expected execution times and incorrect hypothesis outcomes when using this function. Our team has worked diligently to identify the root causes and implement solutions that significantly improve performance and ensure accurate results.
- **Performance Optimization**: Refined the algorithm and code structure of the `limit_distribution_function` to enhance execution efficiency. These optimizations lead to a noticeable reduction in runtime, particularly for large datasets or complex analyses.
- **Bug Fix in Hypothesis Calculation**: Corrected a bug in the formula used for determining hypotheses …
> Optimization and Bug Fix for limit_distribution_function in HypEx

- CODE_OF_CONDUCT.md
- pyproject.toml
This update to the documentation includes the addition of a Code of Conduct to our repository. The purpose of this update is to clearly outline the expectations for behavior within our community and provide a transparent process for handling misconduct. Implementing a Code of Conduct is a step towards fostering a more inclusive, respectful, and collaborative environment for all contributors and users.
New file: CODE_OF_CONDUCT.md - Created a dedicated document outlining the details of the Code of Conduct.
- **CODE_OF_CONDUCT.md**: Introduced a comprehensive Code of Conduct based on the [Contributor Covenant](https://www.contributor-covenant.org/), tailored to our community's specific needs and values.
- This documentation update does not directly relate to any specific issues or pull …
> [DOCS] Documentation Update - Addition of Code of Conduct

- README.md
> [HEI-2] [DOCS] Update README.md

- AAMetaTutorial.ipynb
- hypex/comparators/test_power.py
- hypex/dataset/backends/pandas_backend.py
- hypex/dataset/dataset.py
- hypex/dataset/roles.py
- hypex/experiments/homogeneity.py
- hypex/factory/base.py
- hypex/hypotheses/hypothesis.py
- hypex/hypotheses/schemes/scheme.json
- hypex/splitters/aa.py
- hypex/utils/__init__.py
- hypex/utils/typings.py
- test_config.json
- tutorial_dataset.ipynb
* added types for roles 
* updated parsing roles in Dateset
> Updated roles structure

- examples/tutorials/Tutorial_2_AAtesting.ipynb
- hypex/ab_test/aa_tester.py
This pull request introduces new functions to the statistical analysis module, specifically aimed at calculating the Minimum Detectable Effect (MDE) for unbalanced groups in both binomial and non-binomial contexts. The changes include the implementation of methods that handle the complexity of unbalanced sample sizes and provide a standardized output for easy interpretation.
- Added `__mde_unbalanced_non_binomial` method for non-binomial data which calculates the MDE based on standard deviation and group sizes.
- Added `__mde_unbalanced_binomial` method for binomial data which computes MDE using Cohen's d and fact conversion rates.
- Created `calc_mde_unbalanced_group` as a public interface to calculate MDE depending on the data type (binomial or non-binomial).
- Integrated detailed …
> HEI-5 [FEATURE] Calc MDE 

- examples/tutorials/Tutorial_2_AAtesting.ipynb
- hypex/ab_test/aa_tester.py
> HEI-131 [FEATURE] Chi2 Test in AATest

- examples/tutorials/TutorialAATest.ipynb
- examples/tutorials/TutorialDataset.ipynb
- hypex/dataset/backends/abstract.py
- hypex/dataset/backends/pandas_backend.py
- hypex/dataset/dataset.py
**def dot(other: "Dataset") -> "Dataset"** 
_usage:_ 
1. ds.dot(other_ds) 
**def transpose(roles: Optional[Union[Dict[Union[str, int], ABCRole], List]] = None) -> "Dataset"** 
_usage:_ 
1. ds.transpose() 
2. ds.transpose(roles=['new', 'old', 'my'])
3. ds.transpose(roles={'new': RoleName(), 'old': RoleName()})
**def shuffle(random_state: Optional[int] = None) -> "Dataset"** 
_usage:_ 
1. ds.shuffle() 
2. ds.shuffle(26)
> New math functions

- hypex/matcher.py
- hypex/utils/validators.py
Added permutation test for Matching
> [HEI-253] Feature/permutationg test validation

- examples/tutorials/Tutorial_2_AAtesting.ipynb
- hypex/ab_test/aa_tester.py
- hypex/ab_test/ab_tester.py
Added functionality for AB testing with unbalanced group
> [HEI-252] Feature/unbalanced ab

- hypex/dataset/dataset.py
- hypex/utils/enums.py
**variables**: it will store the numbers that were obtained after working out a certain executor and a certain function in it 
**groups**: it will store Datasets with grouping key after groupby
> [HEI-224] New spaces in ExperimentData

- hypex/analyzers/aa.py
- hypex/comparators/abstract.py
- hypex/dataset/__init__.py
- hypex/dataset/roles.py
- hypex/reporters/aa.py
Correcting errors in pipelines and improving the interpretability of AAReport.
> [HEI-101] Dev/architecture ok not ok

- examples/tutorials/DatasetTutorial.ipynb
- hypex/dataset/backends/pandas_backend.py
- hypex/dataset/dataset.py
ds.columns 
// [a, b]
**ds.rename({'a': 'A', 'b': 'B'})**
> [HEI-249] Added rename function into Dataset

- examples/tutorials/DatasetTutorial.ipynb
- hypex/dataset/backends/pandas_backend.py
- hypex/dataset/dataset.py
**Now it is possible to filter by mask**
ds[ds['a'] == 1]
> [HEI-257] Dev/architecture v10 mask

- hypex/__init__.py
- pyproject.toml
This PR introduces warnings and documentation updates to notify users about the upcoming HypEx architecture changes.
1. **Added Initialization Warning**
- `__init__.py` now includes a `FutureWarning` about the upcoming architecture changes.
- The warning is displayed in both English and Russian.
- The message is also printed to `sys.stderr` to ensure visibility.
2. **Updated README**
- A new section at the top of `README.md` informs users about the upcoming breaking changes.
- The notice includes:
- A description of what is changing.
- A link to new tutorials.
- Installation instructions for both the latest beta version and the legacy version.
- Links to documentation and community support.
- Verified that the warning appears when importing HypEx.
- Checked formatting and correctness of …
> updated last version with old architecture with warnings
